export default [
    {
        id: '0000-0000-0000',
        type: 'universe',
        name: '/',
        label: 'Universe',
        description: 'Root layer for the current universe',
        color: '#fff',
        locked: true,
    },
    {
        id: '0000-0000-1000',
        type: 'system',
        name: '.canvas',
        label: 'Canvas',
        description: 'Canvas system tree',
        color: '#000',
        locked: true,
    },
    {
        id: '0000-0000-2000',
        type: 'system',
        name: '.device',
        label: 'Current device',
        description: 'Current device',
        color: '#fff',
        locked: true,
    },
    {
        id: '0000-0000-2001',
        type: 'system',
        name: '.user',
        label: 'User',
        description: 'Current user',
        color: '#fff',
        locked: true,
    },
    {
        id: '0000-0000-2002',
        type: 'system',
        name: '.session',
        label: 'Session',
        description: 'Current session',
        color: '#fff',
        locked: true,
    },
];
